name: Build Electron App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Electron app (unpacked only)
        run: npx electron-builder --win --x64 --dir --publish=never

      - name: Build Electron app (installer)
        run: npx electron-builder --win --x64 --publish=never

      - name: Upload Unpacked Executable
        uses: actions/upload-artifact@v4
        with:
          name: electron-executable
          path: dist/win-unpacked/AKTIVA-Varovanje.exe

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: aktiva-usmerjevalnik-installer
          path: dist/*.exe
